# Generated by Django 5.2.16 on 2026-07-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissionclaim',
            options={'verbose_name': '提交凭证', 'verbose_name_plural': '提交凭证'},
        ),
    ]
