# Generated by Django 5.2.16 on 2026-07-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user_id'], 'verbose_name': '成员资料', 'verbose_name_plural': '成员资料'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'base_manager_name': 'objects', 'verbose_name': '成员', 'verbose_name_plural': '成员'},
        ),
    ]
