# Generated by Django 5.2.16 on 2026-07-15 14:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('subject_type', models.CharField(choices=[('user', '用户'), ('entry', '内容'), ('comment', '评论')], max_length=20)),
                ('subject_public_id', models.UUIDField()),
                ('reason', models.CharField(choices=[('spam', '垃圾信息'), ('harassment', '骚扰'), ('illegal', '违法风险'), ('other', '其他')], max_length=20)),
                ('details', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('open', '待处理'), ('triaged', '处理中'), ('resolved', '已处理'), ('rejected', '已驳回')], default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ModerationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('none', '不处置'), ('entry.hide', '隐藏内容'), ('entry.restore', '恢复内容'), ('comment.hide', '隐藏评论'), ('comment.restore', '恢复评论'), ('user.suspend', '停用用户'), ('user.restore', '恢复用户')], max_length=80)),
                ('reason', models.CharField(max_length=1000)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderation_decisions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='moderation.report')),
            ],
            options={
                'ordering': ['created_at'],
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'created_at'], name='moderation__status_2a84ce_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['subject_type', 'subject_public_id'], name='moderation__subject_c67fde_idx'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['open', 'triaged'])), fields=('reporter', 'subject_type', 'subject_public_id'), name='moderation_unique_active_report'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolved_at__isnull', True), ('resolved_by__isnull', True), ('status__in', ['open', 'triaged'])), models.Q(('resolved_at__isnull', False), ('resolved_by__isnull', False), ('status__in', ['resolved', 'rejected'])), _connector='OR'), name='moderation_resolution_fields_match_status'),
        ),
    ]
