# Generated by Django 5.2.16 on 2026-07-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderationdecision',
            options={'base_manager_name': 'objects', 'ordering': ['created_at'], 'verbose_name': '审核决定', 'verbose_name_plural': '审核决定'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'base_manager_name': 'objects', 'ordering': ['created_at'], 'verbose_name': '举报', 'verbose_name_plural': '举报'},
        ),
    ]
