# Generated by Django 5.2.16 on 2026-07-15 14:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('site_name', models.CharField(default='MEPPP', max_length=80)),
                ('tagline', models.CharField(blank=True, max_length=160)),
                ('registration_mode', models.CharField(choices=[('open', '开放注册'), ('invite', '仅限邀请'), ('closed', '关闭注册')], default='closed', max_length=10)),
                ('post_max_length', models.PositiveIntegerField(default=2000, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(5000)])),
                ('comment_max_length', models.PositiveIntegerField(default=500, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(2000)])),
                ('max_images_per_post', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('upload_max_bytes', models.PositiveIntegerField(default=5242880, validators=[django.core.validators.MinValueValidator(131072), django.core.validators.MaxValueValidator(20971520)])),
                ('moderation_mode', models.CharField(choices=[('post', '发布后审核'), ('pre', '发布前审核')], default='post', max_length=10)),
                ('comments_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '站点配置',
                'verbose_name_plural': '站点配置',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(unique=True)),
                ('snapshot', models.JSONField()),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuration_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
                'base_manager_name': 'objects',
            },
        ),
    ]
