# Generated by Django 5.2.16 on 2026-07-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configurationrevision',
            options={'base_manager_name': 'objects', 'ordering': ['-version'], 'verbose_name': '配置历史', 'verbose_name_plural': '配置历史'},
        ),
    ]
