# Generated by Django 5.2.16 on 2026-07-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0002_content_pending_and_stable_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['position', 'created_at'], 'verbose_name': '图片附件', 'verbose_name_plural': '图片附件'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'base_manager_name': 'objects', 'ordering': ['created_at', 'pk'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'base_manager_name': 'objects', 'ordering': ['-created_at', '-pk'], 'verbose_name': '内容', 'verbose_name_plural': '内容'},
        ),
        migrations.AlterModelOptions(
            name='entrytopic',
            options={'verbose_name': '内容话题', 'verbose_name_plural': '内容话题'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['slug'], 'verbose_name': '话题', 'verbose_name_plural': '话题'},
        ),
    ]
