# Generated by Django 5.2.16 on 2026-07-16 05:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publishing", "0003_alter_attachment_options_alter_comment_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingComment",
            fields=[],
            options={
                "verbose_name": "待审评论",
                "verbose_name_plural": "待审评论",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("publishing.comment",),
        ),
        migrations.CreateModel(
            name="PendingEntry",
            fields=[],
            options={
                "verbose_name": "待审内容",
                "verbose_name_plural": "待审内容",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("publishing.entry",),
        ),
        migrations.CreateModel(
            name="ContentReviewDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[("approve", "批准公开"), ("reject", "驳回并隐藏")],
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(max_length=500)),
                (
                    "before_state",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("published", "已发布"),
                            ("hidden", "已隐藏"),
                            ("deleted", "已删除"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "after_state",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("published", "已发布"),
                            ("hidden", "已隐藏"),
                            ("deleted", "已删除"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="content_review_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_decisions",
                        to="publishing.comment",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_decisions",
                        to="publishing.entry",
                    ),
                ),
            ],
            options={
                "verbose_name": "内容审核决定",
                "verbose_name_plural": "内容审核决定",
                "ordering": ["-created_at"],
                "base_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["outcome", "-created_at"],
                        name="publishing__outcome_3039bc_idx",
                    ),
                    models.Index(
                        fields=["actor", "-created_at"],
                        name="publishing__actor_i_20c38c_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("comment__isnull", True), ("entry__isnull", False)),
                            models.Q(("comment__isnull", False), ("entry__isnull", True)),
                            _connector="OR",
                        ),
                        name="publishing_review_exactly_one_target",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("before_state", "pending")),
                        name="publishing_review_starts_pending",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("after_state__in", ["published", "hidden"])),
                        name="publishing_review_valid_final_state",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("entry__isnull", False)),
                        fields=("entry",),
                        name="publishing_one_review_per_entry",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("comment__isnull", False)),
                        fields=("comment",),
                        name="publishing_one_review_per_comment",
                    ),
                ],
            },
        ),
    ]
