# Generated by Django 5.2.16 on 2026-07-15 14:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('target_type', models.CharField(max_length=80)),
                ('target_public_id', models.UUIDField(blank=True, null=True)),
                ('request_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'base_manager_name': 'objects',
                'indexes': [models.Index(fields=['action', '-created_at'], name='audit_audit_action_9e2202_idx'), models.Index(fields=['target_type', 'target_public_id'], name='audit_audit_target__484479_idx')],
            },
        ),
    ]
