# Generated by Django 5.2.16 on 2026-07-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditevent',
            options={'base_manager_name': 'objects', 'ordering': ['-created_at'], 'verbose_name': '审计记录', 'verbose_name_plural': '审计记录'},
        ),
    ]
